# Generated by Django 5.2.2 on 2025-06-10 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('WB', 'Wildberries'), ('OZ', 'Ozon'), ('YM', 'Яндекс Маркет'), ('AL', 'AliExpress Russia'), ('SB', 'СберМегаМаркет'), ('CD', 'CDEK Маркет'), ('GT', 'Getmagnet'), ('GO', 'Goods')], max_length=2)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_id', models.CharField(blank=True, max_length=100, null=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sync_frequency', models.IntegerField(default=6)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, verbose_name='External ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Original Price')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Discount Price')),
                ('discount_percentage', models.IntegerField(blank=True, null=True, verbose_name='Discount Percentage')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL')),
                ('deal_url', models.URLField(verbose_name='Deal URL')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Category')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Valid Until')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.marketplace', verbose_name='Marketplace')),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['discount_percentage', 'is_active'], name='deals_deal_discoun_a05ad2_idx'), models.Index(fields=['valid_until'], name='deals_deal_valid_u_978d36_idx'), models.Index(fields=['created_at'], name='deals_deal_created_9d9de4_idx'), models.Index(fields=['is_active'], name='deals_deal_is_acti_b6ead4_idx')],
                'unique_together': {('external_id', 'marketplace')},
            },
        ),
    ]
